In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
type(arr3)

numpy.ndarray

In [9]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#2-d array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(arr2.ndim)# to find the dimension

2


In [12]:
#0-d array
arr=np.array(55)
arr

array(55)

In [13]:
#accessing array element
arr1=np.array([1,2,3,4,5])
print(arr1[0])

1


In [14]:
arr1[3]

4

In [15]:
arr2=np.array([[1,2,3],[4,5,6]])


In [16]:
#2nd element on 1st row
arr2[0,1]

2

In [20]:
#NUMPY STANDS FOR NUMERICAL PYTHON.NUMPY IS A PYTHON LIBRARY USED FOR WORKING WITH ARRAYS IT ALSO HAS FUNCTIONS FOR WORKING
#IN DOMAIN OF LINEAR ALGEBRA,FOURIER TRANSFORM, AND MATRICES NUMPY AIMS TO PROVIDE AN ARRAY OBJECT THAT IS UP TO 50X FASTER THAN TRADITIONAL
#PYTHON LISTS.THE ARRAY OBJECT IN NUMPY IS CALLED NDARRAY,IT PROVIDES A LOT OF SUPPORTING FUNCTIONS THAT MAKE WORKING WITH NDARRAY VERY EASY.Z

In [18]:
arr2[1]

array([4, 5, 6])

In [19]:
arr2[1,1]

5

In [1]:
import numpy as np
arr3=np.array([1,2,3,4,5,6,7])
print(arr3[1:5])


[2 3 4 5]


In [3]:
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[4:])

[5 6 7]


In [4]:
arr5=np.array([1,2,3,4,5,6,7])
print(arr5[:4])

[1 2 3 4]


In [5]:
arr6=np.array([1,2,3,4,5,6,7])
print(arr6[-3:-1])

[5 6]


In [6]:
#return every other element from index 1 to index 5:
arr7=np.array([1,2,3,4,5,6,7])
print(arr7[1:5:2])


[2 4]


In [7]:
#shape of an array:shape that returns a tuple with each index having the number of corresponding emelent
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [8]:
#reshape from 1-d to 2-d
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#reshape from 1-d to 3-d
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
# iterating arrays
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [11]:
#iterate on the element of the following 2-d array:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [12]:
#numpy joining array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [13]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
#join two 2-d arrays along rows(axis=1):
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
#splitting numpy arrays
#splitting is reverse operation of joining.
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [17]:
#random numbers
#numpy offers the random module to work with random numbers.
#generate a random  integer from 0 to 100:
from numpy import random
x=random.randint(100)
print(x)

17


In [18]:
#random module's rand() method returns a random float between 0 to 100:
from numpy import random
x=random.rand()
print(x)

0.2763415103185797


In [19]:
#genarate random array
from numpy import random
x=random.randint(100,size=(5))
print(x)

[25 64 29 44 45]


In [20]:
#A 2-D array with 3 rows,each row containing 5 random integers from 0 to 100:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[34 38 12 32 40]
 [59 46 33 51 53]
 [95 55 75 18 85]]


In [21]:
#generate a 1-D array containing 5 random floats:
from numpy import random
x=random.rand(5)
print(x)

[0.65954637 0.38235701 0.05303907 0.09874129 0.84382972]


In [22]:
#generate a 2-D array with 3 rows,each row containing 5 random numbers:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.46130115 0.51757993 0.16563766 0.1214997  0.97258543]
 [0.47722463 0.07737184 0.79627726 0.92682685 0.7778816 ]
 [0.12182736 0.04954918 0.0734324  0.49301946 0.22629681]]
